---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/README-",
  out.width = "100%"
)
```

# mixed adenoneuroendocrine carcinoma (MANEC)

<!-- badges: start -->
<!-- badges: end -->

Gastric mixed adenoneuroendocrine carcinoma (MANEC) is a heterogeneous tumor composed of adenocarcinoma (ACA) and neuroendocrine carcinoma (NEC) components. This paper is designed to resolve the genomic landscapes and evolutionary clonal origins of this rare cancer. This repository contains the code used in our publication "Precise microdissection of gastric mixed adeno-neuroendocrine carcinoma reveals its genomic landscapes and evolutionary clonal origins". All R code used in the analysis is included.

The main analysis code is stored in **analysis**


## Citations

If you are using code or data in academic research, please cite our paper:

**Miao-Zhen Qiu, Qingjian Chen; Dan-Yang Zheng, Qi Zhao; ...; Rui-Hua Xu; Precise microdissection
of gastric mixed adeno-neuroendocrine carcinoma reveals its genomic landscapes and evolutionary
clonal origins. In submission.**









